"""The gate counts, generated rather than hand-written.

`stats.generated.json` (see `stats.py`) makes upstream DATA drift legible. This is the same
pattern pointed at the other family of rotting numbers: how big the gates are.

The Python test total moved **four times in a single session** — 491 → 493 → 498 → 510 — and
each move required hand-editing `CLAUDE.md`'s gates table, which is itself a hand-written
measurement inside the file whose own rule says *"Measurements belong in generated output,
because hand-written ones rot."* The 442/49 pair in `.github/actions/setup/action.yml` was
corrected in one commit and was stale again two commits later, by this repo's own doing.

## The boundary, decided deliberately

The epic (#10) asks for this to be stated rather than half-done, so that the figures left by
hand do not read as authoritative:

- `python_tests` — **generated here.** `pytest --collect-only` takes 0.4 s and needs no
  `data/`, no warehouse and no `node_modules`, so it can gate inside `make check`.
- app test total — **not generated.** `vitest list` works and takes ~4 s, but needs
  `app/node_modules`; wiring it into `make check` would break that gate on a clone that has
  not yet run `make install`.
- smoke check count — **not generated.** Only a real `next build` plus a served port produces
  it, at roughly five minutes.
- page weights — **not generated**, for the same reason.
- entity and fact counts — **generated elsewhere**, by `make stats`, from the warehouse.

A figure in the "no" column is not thereby trustworthy. It is hand-maintained and must be
re-measured when quoted — which is exactly the rule `CLAUDE.md` already carries, now scoped to
a much smaller set.

The count deliberately does NOT include the skipped total. Skips are decided at runtime by
`Path.exists()` checks against `data/` and `upgauge.duckdb`, so producing them means running
the suite in an environment that has neither — which is a CI job (`verify.yml`), not a
sub-second collection.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

GATES_PATH = Path(__file__).parent / "reference" / "gates.generated.json"
REPO = Path(__file__).parents[1]

_COLLECTED = re.compile(r"^(\d+) tests? collected", re.MULTILINE)


def python_test_count() -> int:
    """Total tests pytest collects. Collection only — nothing is executed.

    Runs pytest as a subprocess rather than in-process: a nested `pytest.main()` inherits the
    running session's plugins and config and would report the count of whatever invoked it.
    """
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-p", "no:cacheprovider"],
        cwd=REPO,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"collection failed:\n{result.stdout}\n{result.stderr}")
    match = _COLLECTED.search(result.stdout)
    if not match:
        raise RuntimeError(
            "no 'N tests collected' line in pytest output -- the reporter format changed, and "
            f"a silent 0 here would gate nothing:\n{result.stdout[-2000:]}"
        )
    count = int(match.group(1))
    if count <= 0:
        raise RuntimeError(f"collected {count} tests -- refusing to pin a vacuous count")
    return count


def collect() -> dict[str, int]:
    return {"python_tests": python_test_count()}


def write_gates(out: Path = GATES_PATH) -> None:
    payload: dict[str, object] = {"gates": collect()}
    payload["_generated"] = (
        "GENERATED by `make gate-counts`. Do not hand-edit. `make check` diffs this, so a diff "
        "means a test was added or removed without regenerating -- run `make gate-counts` and "
        "commit the result alongside the test. See pipeline/gatecounts.py for which gate "
        "figures are deliberately NOT generated, and why."
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")


def main(argv: list[str] | None = None) -> int:
    """`make gate-counts`."""
    import argparse

    parser = argparse.ArgumentParser(description="Regenerate the gate-counts artifact.")
    parser.add_argument("--write", action="store_true", help=f"Regenerate {GATES_PATH}")
    args = parser.parse_args(argv)
    if not args.write:
        parser.error("nothing to do -- pass --write")
    write_gates()
    print(f"wrote {GATES_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
